### ISSUE TITLE
Fails to run over http2 transport

### ISSUE THREAD

**Issue by kptfh** [jetty-project/jetty-reactive-httpclient#12]
Fails with `java.io.IOException: 6/invalid_frame_length` while trying to run over http2 transport.
Here is the test [SmokeTest] (https://github.com/Playtika/feign-reactive/blob/feature/jetty-http2/feign-reactor-jetty-http2/src/test/java/reactivefeign/jetty/SmokeTest.java)

**Comment by sbordet** [comment]
The client is sending clear-text HTTP/2 with prior-knowledge (i.e. without upgrade), and the server replies with `426 Upgrade Required`.
You need to configure the server to support prior-knowledge clear-text HTTP/2, as Jetty's `HttpClient` cannot yet perform upgrades to HTTP/2.

**Comment by kptfh** [comment]
Hi Simone.
1) It's not obvious for me how do you get to this error code `426 Upgrade Required`. 
2) Don't you know how to configure Wiremock which is based on Jetty Server in proper way to accept HTTP/2 plain text calls?

**Comment by sbordet** [comment]
1. Wireshark trace
2. No, I don't know - will have a look.

**Comment by kptfh** [comment]
JFY: Here is the code to config Wiremock to Http2c

```
return WireMockConfiguration.wireMockConfig()
                .httpServerFactory((options, adminRequestHandler, stubRequestHandler) ->
                        new JettyHttpServer(options, adminRequestHandler, stubRequestHandler) {
                            @Override
                            protected ServerConnector createHttpConnector(
                                    String bindAddress,
                                    int port,
                                    JettySettings jettySettings,
                                    NetworkTrafficListener listener) {
                                HttpConfiguration httpConfig = createHttpConfig(jettySettings);
                                return createServerConnector(
                                        bindAddress,
                                        jettySettings,
                                        port,
                                        listener,
                                        new HTTP2CServerConnectionFactory(httpConfig)
                                );
                            }
                        });
```
