### ISSUE TITLE
Can't use 1.0.3 client with latest version of jetty-client 9.4.22

### ISSUE THREAD

**Issue by kptfh** [jetty-project/jetty-reactive-httpclient#17]
java.lang.AbstractMethodError: Receiver class org.eclipse.jetty.reactive.client.internal.ResponseListenerPublisher does not define or inherit an implementation of the resolved method abstract onContent(Lorg/eclipse/jetty/client/api/Response;Ljava/util/function/LongConsumer;Ljava/nio/ByteBuffer;Lorg/eclipse/jetty/util/Callback;)V of interface org.eclipse.jetty.client.api.Response$DemandedContentListener.

**Comment by sbordet** [comment]
Thanks for the report, we are working on a new release of Jetty that will trigger a new release of this project.

**Comment by priyansms** [comment]
When the release would be available ?

**Comment by sbordet** [comment]
Soon, we are preparing Jetty 9.4.23 and when that is available there will be a `jetty-reactive-httpclient` 1.1.0 release.

**Comment by kptfh** [comment]
just to softly remind :)

**Comment by joakime** [comment]
Jetty 9.4.24.v20191120 is now released, if that helps?

**Comment by kptfh** [comment]
No, need jetty-reactive-httpclient 1.1.0 release. Currently the latest version of Spring is broken.

**Comment by sbordet** [comment]
Reactive HttpClient 1.1.0 released, with dependency on Jetty 9.4.24.
