### ISSUE TITLE
Spring Framework is interested in this client

### ISSUE THREAD

**Issue by joakime** [jetty-project/jetty-reactive-httpclient#2]
There is interest in this client from the Spring folks - https://jira.spring.io/browse/SPR-15092

**Comment by joakime** [comment]
Mentioning @sbordet @gregw to get them to see notification.

**Comment by sbordet** [comment]
I have been talking to @sdeleuze about the integration, work is ongoing.

**Comment by sdeleuze** [comment]
Indeed I am working on that with @sbordet support so feel free to close this issue ;-)
