### ISSUE TITLE
h2c fails on 9.4.23.v20191118 Jetty Server and 1.1.0-SNAPSHOT  jetty-reactive-httpclient

### ISSUE THREAD

**Issue by kptfh** [jetty-project/jetty-reactive-httpclient#20]
After upgrade of ReactiveFeign Jetty-based implementation to 9.4.23.v20191118 Jetty Server and 1.1.0-SNAPSHOT jetty-reactive-httpclient H2c test began to fail. H1 version works correctly.

Test just tries to run 500 queries in parallel.
I get a lot of this warnings on server side
` [qtp1378612814-18] WARN  org.eclipse.jetty.server.HttpOutput - java.io.IOException: Closed while Pending/Unready`
And then on client 
`java.io.IOException: cancel_stream_error`

Last stable version that this test was passing is 9.4.14 and 1.0.2 jetty-reactive-httpclient

Here is the link to this test [AllFeaturesTest](https://github.com/Playtika/feign-reactive/blob/latest-jetty/feign-reactor-jetty/src/test/java/reactivefeign/jetty/h2c/AllFeaturesTest.java)
To run it locally you need to have 1.1.0-SNAPSHOT  jetty-reactive-httpclient in local maven repository.

**Comment by sbordet** [comment]
@kptfh I'm looking into this.

**Comment by kptfh** [comment]
Probably issue on server side (which is also Jetty based) because Java 11 ReactiveFeign test is also failing
[Java 11 ReactiveFeign against j2c Jetty server](https://github.com/Playtika/feign-reactive/blob/latest-jetty/feign-reactor-java11/src/test/java/reactivefeign/java11/h2c/AllFeaturesTest.java)

**Comment by sbordet** [comment]
This is an issue related to bad usage of the Servlet 3.1 async I/O APIs from Spring.

We have been able to reproduce the test failure with 9.4.23 but also 9.4.14 - the code that handles this case did not change.

We have filed eclipse/jetty.project#4331 to track the behavior from the Servlet Specification point of view, but Spring should try harder to avoid calling Servlet APIs such as `ServletOutputStream.close()` or `AsyncContext.complete()` when previous writes are pending.

**Comment by kptfh** [comment]
It's quite strange. Http1 version of the test works well. 
[Jetty ReactiveFeign against h1 Jetty server](https://github.com/Playtika/feign-reactive/blob/latest-jetty/feign-reactor-jetty/src/test/java/reactivefeign/jetty/h1/AllFeaturesTest.java)

**Comment by sbordet** [comment]
The HTTP/1.1 version works well because the (small) writes are never stalled and all happen in different connections.

For HTTP/2, the concurrency makes it so a request trying to write the response content is stalled because other threads are currently writing to the single connection that HTTP/2 uses.
Because the write is non-blocking, it queues the buffer to write and return immediately, allowing the code that calls `AsyncContext.complete()` to run before the write is finished.

**Comment by kptfh** [comment]
Got it. Thanks

**Comment by sbordet** [comment]
@kptfh are you going to raise an issue to the Spring project?

**Comment by kptfh** [comment]
@sbordet here it is [issue](https://github.com/spring-projects/spring-framework/issues/24050)
Please, check it and comment.
