### ISSUE TITLE
Provide BlockHoundIntegration

### ISSUE THREAD

**Issue by kptfh** [jetty-project/jetty-reactive-httpclient#21]
builder.allowBlockingCallsInside("org.eclipse.jetty.client.AbstractConnectionPool", "acquire");
builder.allowBlockingCallsInside("org.eclipse.jetty.client.MultiplexConnectionPool", "acquire");
builder.allowBlockingCallsInside("org.eclipse.jetty.util.BlockingArrayQueue", "poll");
builder.allowBlockingCallsInside("org.eclipse.jetty.util.BlockingArrayQueue", "offer");

**Comment by kptfh** [comment]
//java.net.InMemoryCookieStore.get
builder.allowBlockingCallsInside("org.eclipse.jetty.client.HttpConnection", "normalizeRequest");

**Comment by kptfh** [comment]
builder.allowBlockingCallsInside("org.eclipse.jetty.client.MultiplexConnectionPool", "lock");

**Comment by sbordet** [comment]
@kptfh I'm sorry you have to detail more exactly what this is. Seems a lot of false positives to me.

**Comment by kptfh** [comment]
Sorry for delay. Spent a lot of time adding exclusions to BlockHound to pass my tests.
There is an option to include BlockHoundIntegration implementation class into library. 
Then BlockHound will be able automatically add this exclusions and it will save a lot of times to all who will run BlockHound tests while using your library .

**Comment by kptfh** [comment]
Here is the final list of exclusions that allows to pass tests
```
            builder.allowBlockingCallsInside("org.eclipse.jetty.client.AbstractConnectionPool", "acquire");
            builder.allowBlockingCallsInside("org.eclipse.jetty.client.MultiplexConnectionPool", "acquire");
            builder.allowBlockingCallsInside("org.eclipse.jetty.client.MultiplexConnectionPool", "lock");
            builder.allowBlockingCallsInside("org.eclipse.jetty.util.BlockingArrayQueue", "poll");
            builder.allowBlockingCallsInside("org.eclipse.jetty.util.BlockingArrayQueue", "offer");
            builder.allowBlockingCallsInside("org.eclipse.jetty.util.BlockingArrayQueue", "peek");
            //java.net.InMemoryCookieStore.get
            builder.allowBlockingCallsInside("org.eclipse.jetty.client.HttpConnection", "normalizeRequest");
            builder.allowBlockingCallsInside("java.util.concurrent.FutureTask", "handlePossibleCancellationInterrupt");
```

**Comment by sbordet** [comment]
@kptfh I'm sorry but there are no blocking call inside `AbstractConnectionPool.acquire()` nor inside `HttpConnection.normalizeRequest()`, so I have doubts that the tool's report are accurate.

**Comment by kptfh** [comment]
BlockHound reports on all operations with Lock that are present in all these calls.

**Comment by sbordet** [comment]
@kptfh well, there are no Locks in those two calls so the tool does not seems to work properly to me.

**Comment by kptfh** [comment]
They are down the stack. In case of `AbstractConnectionPool.acquire()` it occur in `activate`

**Comment by kptfh** [comment]
May try to provide full stack trace for each case

**Comment by sbordet** [comment]
@kptfh can I ask what's the point of this?
Your analysis has already showed that the reactive wrapper around `HttpClient` does not seem to have problems.

The Jetty `HttpClient` implementation may change at any time for bug fixes, etc. so the list of "allows" that is valid for one version may not be valid for another version.

Thanks

**Comment by kptfh** [comment]
Missed that this is just wrapper. So it's better to place it in HttpClient project.

**Comment by sbordet** [comment]
> So it's better to place it in HttpClient project.

No, there we don't care about being "reactive".

**Comment by kptfh** [comment]
It's about being non-blocking.

**Comment by sbordet** [comment]
> It's about being non-blocking.

Obviously the tool is not about that. 

Try to run it against JDK's NIO which is completely non-blocking, and it will find a million false positives (unless the tool does not look inside JDK classes).

Same for Jetty's `HttpClient`: it's non-blocking but the tool cannot figure it out, so I don't see how the tool is any useful, sorry.
