### ISSUE TITLE
Metrics integration for Jetty reactive httpclient

### ISSUE THREAD

**Issue by patpatpat123** [jetty-project/jetty-reactive-httpclient#221]
Hello team,

This is my first post in this repo, if not anything else, just wanted to say big thanks for this cool project.

Just wanted to reach out asking for a possible feature / enhancement request.

Would it be possible to add metrics integration to this project? (For instance, micrometer)

For example, the netty client (just taking as an example, not saying it is the correct way) offers this construct :

```
public reactor.netty.http.client.HttpClient getHttpClient() {
        return reactor.netty.http.client.HttpClient
                .create()
                .metrics(true, Function.identity())  // <-- this is super cool
                .wiretap(true)
                .protocol(HttpProtocol.HTTP11)
                ;
    }
```

With this, out of the box, one would get very useful metrics such as:

```
reactor_netty_bytebuf_allocator_active_direct_memory
reactor_netty_bytebuf_allocator_active_heap_memory
reactor_netty_bytebuf_allocator_chunk_size
reactor_netty_bytebuf_allocator_direct_arenas
reactor_netty_bytebuf_allocator_heap_arenas
reactor_netty_bytebuf_allocator_normal_cache_size
reactor_netty_bytebuf_allocator_small_cache_size
reactor_netty_bytebuf_allocator_threadlocal_caches
reactor_netty_bytebuf_allocator_used_direct_memory
reactor_netty_bytebuf_allocator_used_heap_memory
reactor_netty_connection_provider_active_connections
reactor_netty_connection_provider_idle_connections
reactor_netty_connection_provider_max_connections
reactor_netty_connection_provider_max_pending_connections
reactor_netty_connection_provider_pending_connections
reactor_netty_connection_provider_total_connections
reactor_netty_eventloop_pending_tasks
reactor_netty_http_client_address_resolver
reactor_netty_http_client_connect_time
reactor_netty_http_client_data_received
reactor_netty_http_client_data_received_time
reactor_netty_http_client_data_sent
reactor_netty_http_client_data_sent_time
reactor_netty_http_client_response_time
reactor_netty_http_client_tls_handshake_time

```

Would it be possible for this repo to offer a likewise feature, please?
It will make this project much more production-ready with greater observability.

Thank you so much!

**Comment by sbordet** [comment]
What metrics are you interested in?

I ask because typically metrics depend on the application: some are interested in certain metrics that for others are irrelevant, and viceversa.

Depending on the metric you are interested, you can typically obtain it with much more accuracy by configuring `HttpClient` appropriately.
For example you can use `MonitoredQueuedThreadPool` instead of the regular `ThreadPool`.
The default `ByteBufferPool` implementations already export a number of interesting metrics.

For request/response metrics, it's typically very easy to write additional listeners that would gather the metrics you are interested in, see for example the various listeners documented at https://www.eclipse.org/jetty/documentation/jetty-10/programming-guide/index.html#pg-client-http-non-blocking.

This approach would allow you to gather histogram data of request metrics, not just some average (that are typically useless).

**Comment by patpatpat123** [comment]
Thank you @sbordet for the answer.

Let's start with some very simple metrics: time/count and status.

time/count: For instance, I have two requests one after another. One took 10ms to complete, one took 220ms to complete.
It would be great to have the metrics showing the time, which allow something like ```_/|_``` (drawing a spike with the 10ms and 220ms) That way, we know there is a requests which took 10ms, and another one which took 22 times longer.

With this time info, we can infer the count, since one requests took 10ms, one took 220ms, so we know between those 230 ms, two requests happened.

Finally, would be great to get the status, for instance, getting metrics which count the number of 200 responses vs the number of 500 responses.

Is this currently supported? How to get those please?

**Comment by sbordet** [comment]
I added, as a simple example, https://github.com/jetty-project/jetty-reactive-httpclient/blob/2.0.x/src/test/java/org/eclipse/jetty/reactive/client/MetricsTest.java. 

You can see how to use the `HttpClient` events to gather your own metrics.

You can, less efficiently, also use reactive events via `ReactiveRequest.requestEvents()` and `ReactiveRequest.responseEvents()`.

I used `HdrHistogram` to gather the response times in a nice histogram, and printed it out via Jetty's performance helper class `HistogramSnapshot`.

Note that `MetricsTest` is just a simple example and should not be taken as an example to do proper load testing (if you are interested, read https://github.com/jetty-project/jetty-load-generator).

**Comment by patpatpat123** [comment]
Thank you for the sample.

I was thinking of something more like micrometer integration, where adding a listener would offer out of the box those metrics.
Other http clients, such as Okhttp, Apache http client, Netty do support those kind of metrics integration out of the box without having user to reimplement.

But the example is very useful, thank you and closing
