### ISSUE TITLE
2.x.x and 3.x.x dependency issues

### ISSUE THREAD

**Issue by kohoward** [jetty-project/jetty-reactive-httpclient#38]
I am getting NoClassDefFoundError. On inspecting the issue, I find that PublisherContentProvider cannot be resolved.

Rolling back to 1.x.x works fine.

```
	@Override
	public Mono<Void> writeWith(Publisher<? extends DataBuffer> body) {
		return Mono.<Void>create(sink -> {
			ReactiveRequest.Content content = Flux.from(body)
					.map(buffer -> toContentChunk(buffer, sink))
					.as(chunks -> ReactiveRequest.Content.fromPublisher(chunks, getContentType()));
			this.jettyRequest.content(new PublisherContentProvider(content));
			sink.success();
		})
				.then(doCommit(this::completes));
	}
```

**Comment by sbordet** [comment]
`PublisherContentProvider` is an internal class that should not be used by application code.

You should use `reactiveRequest.content(content)` instead.

**Comment by kohoward** [comment]
Just to clarify my application code is NOT using PublisherContentProvider. I am simply using jetty-reactive-httpclient. The library is throwing an error.

**Comment by sbordet** [comment]
@kohoward have you opened an issue to "the library"? What library it is, Spring WebFlux?

**Comment by kohoward** [comment]
The issues lies with jetty-reactive-httpclient, specifically in the code in the first post.

The snippet of code is from jetty-reactive-httpclient

**Comment by sbordet** [comment]
> The snippet of code is from jetty-reactive-httpclient

There is no such snippet of code in this project.
