### ISSUE TITLE
Issue closed without investigation

### ISSUE THREAD

**Issue by kohoward** [jetty-project/jetty-reactive-httpclient#40]
I have noticed you have closed https://github.com/jetty-project/jetty-reactive-httpclient/issues/38

**Problem is not related to my application code.** This library is internally referencing something that does not exist.

I am just being persistent here so you do not assume this is not a problem. This will be my final attempt to bring your attention to this.

**Comment by sbordet** [comment]
@kohoward I understand the "faulty" code is not in your application code.
However, it's not in this library code either.

Thank you for being persistent, but I can't find the code you reference in #38, and even grepping for `PublisherContentProvider` in the `2.0.x` and `3.0.x` branches yields zero results.

My guess is that you are using another library that uses this library, and it's the other library that has the faulty code.

If you find the faulty code in this library, can you please point me to the file that has the faulty code?
