### ISSUE TITLE
OSGi Headers are missing

### ISSUE THREAD

**Issue by flyaruu** [jetty-project/jetty-reactive-httpclient#6]
Unlike the rest of Jetty, the reactive client has no OSGi headers. I think it makes sense to have them.

**Comment by sbordet** [comment]
@flyaruu can you please test the latest code to see if it works in OSGi for you ?

**Comment by flyaruu** [comment]
I'll do that!

**Comment by flyaruu** [comment]
Works for me! Will this library be added to the Jetty distribution in general (for me the p2 repo would be most convenient)?
